---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EnvironmentValue:
    Type: String
    Default: local
    AllowedValues:
      - local
      - dev
      - qa
      - prod
    Description: The environment the stack is being deployed into

Resources:
  EC2BaseInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${EnvironmentValue}-ec2-base-instance-role"
      Description: IAM Instance Profile for base (generic) EC2 instances
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: ec2-describe-tags
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeTags
                Resource: "*"
        - PolicyName: ec2-set-name-tag
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateTags
                Resource: "*"
                Condition:
                  ForAllValues:StringEquals:
                    aws:TagKeys: # Only allow setting the Name tag
                      - Name
                  StringEquals:
                    aws:ARN: ${ec2:SourceInstanceARN} # Only allow the instance to modify tags on itself
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  EC2BaseInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - Ref: EC2BaseInstanceRole

  InstanceProfileParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /shared/iam/instance-profiles/ec2-base
      Type: String
      Value: !Ref EC2BaseInstanceProfile
      Description: !Sub "${EnvironmentValue} ec2-base instance profile"
